# Generated by Django 6.0.3 on 2026-04-06 21:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_goal_minutes",
                    models.PositiveIntegerField(
                        default=120, help_text="Daily study goal in minutes"
                    ),
                ),
                (
                    "weekly_goal_minutes",
                    models.PositiveIntegerField(
                        default=600, help_text="Weekly study goal in minutes"
                    ),
                ),
                (
                    "sns_notifications_enabled",
                    models.BooleanField(
                        default=True, help_text="Receive SNS push notifications"
                    ),
                ),
                (
                    "sns_endpoint_arn",
                    models.CharField(
                        blank=True,
                        help_text="User SNS subscription ARN",
                        max_length=512,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="General",
                        help_text="Subject or topic tag",
                        max_length=100,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, help_text="Total duration in seconds", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Session",
                "verbose_name_plural": "Study Sessions",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="timer_study_user_id_c552f6_idx"
                    ),
                    models.Index(
                        fields=["user", "started_at"],
                        name="timer_study_user_id_bdd88b_idx",
                    ),
                ],
            },
        ),
    ]
